[client]

toolbarMode = "minimal"



[ui]

hideTopBar = false



[theme]

base = "dark"

primaryColor = "#3b82f6"

backgroundColor = "#020617"

secondaryBackgroundColor = "#0f172a"

textColor = "#e2e8f0"

font = "sans serif"

